wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
epochs:
  desc: null
  value: 20
num_classes:
  desc: null
  value: 3
dropout:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703843498.947108
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 48
      - 49
      - 53
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.1
      6: 4.35.2
      8:
      - 5
      13: linux-x86_64
